import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import SideBar from "@/components/sidebar";
import PageNavMain from "@/components/pagenavmain";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ibrejetiba",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <div className="flex flex-col">
          <PageNavMain />
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  );
}
